### ISSUE TITLE
Console error that cannot be suspended

### ISSUE THREAD

**Issue by wtrocki** [aerogear/aerogear-js-sdk#329]
## Bug Report

When starting SDK in any app following error appears a couple of times:
```
vendor.js:21535 Error when sending metrics {"stack":"Error: Metrics server configuration is missing. Metrics will be disabled.\n    at MetricsService.
```

there is no way to suspend it. Not having metrics enabled is not an error so we might remove this to not obfuscate logs.

ping @austincunningham

**Comment by austincunningham** [comment]
introduced here https://github.com/aerogear/aerogear-js-sdk/blob/cf506b0c13fa19c211c1b32741916857db7ce09c/packages/core/src/metrics/MetricsService.ts#L47

**Comment by wtrocki** [comment]
Actually, it is being printed 3 times because of code here:
https://github.com/aerogear/aerogear-js-sdk/blob/2bef55d152bb6149a630a0ee6e8bc16c935602ec/packages/core/src/metrics/MetricsService.ts#L82-L84

This is caused by https://github.com/aerogear/aerogear-js-sdk/commit/d5c0497d8e0d5a8437d6602ed0c6ae9ff71b19b6

We always send metrics now (even when there is no config)
